services:
  CleanArchitecture.orderManagement.api:
    image: ${DOCKER_REGISTRY-}cleanArchitectureorderapi
    build:
      context: .
      dockerfile: src/CleanArchitecture.OrderManagement.Api/Dockerfile
