services:  
 cleanarchitecture.ordermanagement.api:  
   image: ${DOCKER_REGISTRY-}cleanarchitectureordermanagementapi  
   build:  
       context: .  
       dockerfile: src/CleanArchitecture.Order.Api/Dockerfile  
 cleanarchitecture.ordermanagement.db:  
   image: postgres:latest  
   container_name: ordermanagement.Db  
   environment:  
     - POSTGRES_DB=ordermanagement_db  
     - POSTGRES_USER=postgres  
     - POSTGRES_PASSWORD=postgres  
   volumes:   
     - ./.containers/database:/var/lib/postgresql/data  
   ports:  
     - "5432:5432"